theme: jekyll-theme-cayman
title: [Sid Ferreira's Resume]
description: "Proud father, happy developer, enjoys emoji and gifs<br><small>Florianopolis / Brazil - sid&commat;ferreiraz&period;com&period;br</small>"
google_analytics: [UA-97627426-1]
