theme: jekyll-theme-cayman
title: "Sid Ferreira"
description: "Proud father, happy developer, enjoys emoji and gifs<br><small>Florianopolis / Brazil (UTC-3) - sid&commat;ferreiraz&period;com&period;br</small>"
google_analytics: [UA-97627426-1]
gems:
  - jekyll-seo-tag
social:
  name: Sid Ferreira
  links:
    - https://twitter.com/sidferreiraz
    - https://www.facebook.com/sidferreiraz
    - https://www.linkedin.com/in/sidferreira/
    - https://github.com/sidferreira
image:
  path: /assets/img/sidferreira.jpg
  height: 512
  width: 512
