theme: jekyll-theme-minimal
title: [Welcome to my Resume ]
description: [ This is a work in progress. I've started as a new pattern for my resume and I'm still tinkering it. But, the most important stuff is there! ]
