theme: jekyll-theme-cayman
title: [Sid Ferreira]
description: "Proud father, happy developer, enjoys emoji and gifs<br><small>Florianopolis / Brazil (UTC-3) - sid&commat;ferreiraz&period;com&period;br</small>"
google_analytics: [UA-97627426-1]
