theme: jekyll-theme-cayman
title: "Sid Ferreira - Resume"
description: "Remote Developer - Florianopolis / Brazil (UTC-3) - sid&commat;ferreiraz&period;com&period;br"
description_alt: "Proud father, happy developer, enjoys emoji and gifs<br><small>Florianopolis / Brazil (UTC-3) - sid&commat;ferreiraz&period;com&period;br</small>"
google_analytics: [UA-97627426-1]
gems:
  - jekyll-seo-tag
site: 
  title: "Sid Ferreira - Resume"
  description: "Remote Developer - Florianopolis / Brazil (UTC-3) - sid&commat;ferreiraz&period;com&period;br"
social:
  name: Sid Ferreira
  links:
    - https://twitter.com/sidferreiraz
    - https://www.facebook.com/sidferreiraz
    - https://www.linkedin.com/in/sidferreira/
    - https://github.com/sidferreira
image: https://avatars3.githubusercontent.com/u/143615
logo: https://avatars3.githubusercontent.com/u/143615
